sequenceDiagram
    participant consumer as API Consumer
    participant sales as Sales API
    participant customer as Customer API
    participant insurer as Insurer Backend
    participant integration as Industri and Goverment APIs
    consumer->>integration : Search addresses or vehicles
    consumer->>sales : Get price for product
    sales->>insurer : Get price
    consumer->>integration : Search persons or organizations
    consumer->>sales : Create quote for customer
    sales->>integration : Assess customer 
    sales->>customer : Create quote account
    customer->>insurer : Create price/quote  & notify customer
    consumer->>sales : Accept created quote 
    consumer->>integration : Sign created quote
    consumer->>sales : Activate created quote 
